// config actions
export const UPDATE_CALLSIGN = "UPDATE_CALLSIGN";
export const UPDATE_RADIO = "UPDATE_RADIO";
export const UPDATE_SATELLITES = "UPDATE_SATELLITES";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CHANNEL_START = "UPDATE_CHANNEL_START";
export const UPDATE_CHANNEL_SPREAD = "UPDATE_CHANNEL_SPREAD";
export const UPDATE_POWER = "UPDATE_POWER";
