// config actions
export const UPDATE_CALLSIGN = "UPDATE_CALLSIGN";
export const UPDATE_RADIO = "UPDATE_RADIO";
export const ACTIVATE_SATELLITE = "ACTIVATE_SATELLITE";
export const DEACTIVATE_SATELLITE = "DEACTIVATE_SATELLITE";
